/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthhistoryHistoryRouteImport } from './routes/_auth/(history)/history'
import { Route as AuthdashboardDashboardRouteImport } from './routes/_auth/(dashboard)/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthhistoryHistoryRoute = AuthhistoryHistoryRouteImport.update({
  id: '/_auth/(history)/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthdashboardDashboardRoute = AuthdashboardDashboardRouteImport.update({
  id: '/_auth/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthdashboardDashboardRoute
  '/history': typeof AuthhistoryHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthdashboardDashboardRoute
  '/history': typeof AuthhistoryHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/_auth/(dashboard)/dashboard': typeof AuthdashboardDashboardRoute
  '/_auth/(history)/history': typeof AuthhistoryHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/history'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/_auth/(dashboard)/dashboard'
    | '/_auth/(history)/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthdashboardDashboardRoute: typeof AuthdashboardDashboardRoute
  AuthhistoryHistoryRoute: typeof AuthhistoryHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/(history)/history': {
      id: '/_auth/(history)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthhistoryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/(dashboard)/dashboard': {
      id: '/_auth/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthdashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthdashboardDashboardRoute: AuthdashboardDashboardRoute,
  AuthhistoryHistoryRoute: AuthhistoryHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
